package com.school.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class LikesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public LikesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public LikesExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public LikesExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        LikesExample example = new LikesExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public LikesExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public LikesExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table likes
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdIsNull() {
            addCriterion("like_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdIsNotNull() {
            addCriterion("like_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdEqualTo(Integer value) {
            addCriterion("like_user_id =", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdNotEqualTo(Integer value) {
            addCriterion("like_user_id <>", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdGreaterThan(Integer value) {
            addCriterion("like_user_id >", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_user_id >=", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdLessThan(Integer value) {
            addCriterion("like_user_id <", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("like_user_id <=", value, "likeUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeUserIdLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeUserIdIn(List<Integer> values) {
            addCriterion("like_user_id in", values, "likeUserId");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdNotIn(List<Integer> values) {
            addCriterion("like_user_id not in", values, "likeUserId");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdBetween(Integer value1, Integer value2) {
            addCriterion("like_user_id between", value1, value2, "likeUserId");
            return (Criteria) this;
        }

        public Criteria andLikeUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("like_user_id not between", value1, value2, "likeUserId");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdIsNull() {
            addCriterion("liked_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdIsNotNull() {
            addCriterion("liked_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdEqualTo(Integer value) {
            addCriterion("liked_user_id =", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdNotEqualTo(Integer value) {
            addCriterion("liked_user_id <>", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdGreaterThan(Integer value) {
            addCriterion("liked_user_id >", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("liked_user_id >=", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdLessThan(Integer value) {
            addCriterion("liked_user_id <", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("liked_user_id <=", value, "likedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedUserIdLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedUserIdIn(List<Integer> values) {
            addCriterion("liked_user_id in", values, "likedUserId");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdNotIn(List<Integer> values) {
            addCriterion("liked_user_id not in", values, "likedUserId");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdBetween(Integer value1, Integer value2) {
            addCriterion("liked_user_id between", value1, value2, "likedUserId");
            return (Criteria) this;
        }

        public Criteria andLikedUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("liked_user_id not between", value1, value2, "likedUserId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameIsNull() {
            addCriterion("like_school_name is null");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameIsNotNull() {
            addCriterion("like_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameEqualTo(String value) {
            addCriterion("like_school_name =", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameNotEqualTo(String value) {
            addCriterion("like_school_name <>", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameGreaterThan(String value) {
            addCriterion("like_school_name >", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("like_school_name >=", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameLessThan(String value) {
            addCriterion("like_school_name <", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("like_school_name <=", value, "likeSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikeSchoolNameLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("like_school_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameLike(String value) {
            addCriterion("like_school_name like", value, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameNotLike(String value) {
            addCriterion("like_school_name not like", value, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameIn(List<String> values) {
            addCriterion("like_school_name in", values, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameNotIn(List<String> values) {
            addCriterion("like_school_name not in", values, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameBetween(String value1, String value2) {
            addCriterion("like_school_name between", value1, value2, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikeSchoolNameNotBetween(String value1, String value2) {
            addCriterion("like_school_name not between", value1, value2, "likeSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameIsNull() {
            addCriterion("liked_school_name is null");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameIsNotNull() {
            addCriterion("liked_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameEqualTo(String value) {
            addCriterion("liked_school_name =", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameNotEqualTo(String value) {
            addCriterion("liked_school_name <>", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameNotEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameGreaterThan(String value) {
            addCriterion("liked_school_name >", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameGreaterThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("liked_school_name >=", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameGreaterThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameLessThan(String value) {
            addCriterion("liked_school_name <", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameLessThanColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("liked_school_name <=", value, "likedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLikedSchoolNameLessThanOrEqualToColumn(Likes.Column column) {
            addCriterion(new StringBuilder("liked_school_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameLike(String value) {
            addCriterion("liked_school_name like", value, "likedSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameNotLike(String value) {
            addCriterion("liked_school_name not like", value, "likedSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameIn(List<String> values) {
            addCriterion("liked_school_name in", values, "likedSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameNotIn(List<String> values) {
            addCriterion("liked_school_name not in", values, "likedSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameBetween(String value1, String value2) {
            addCriterion("liked_school_name between", value1, value2, "likedSchoolName");
            return (Criteria) this;
        }

        public Criteria andLikedSchoolNameNotBetween(String value1, String value2) {
            addCriterion("liked_school_name not between", value1, value2, "likedSchoolName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table likes
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private LikesExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        protected Criteria(LikesExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public LikesExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(Likes.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(Likes.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table likes
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table likes
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        void example(com.school.model.LikesExample example);
    }
}