package com.school.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Likes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.likeUserId
     *
     * @mbg.generated
     */
    private Integer likeuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.likedUserId
     *
     * @mbg.generated
     */
    private Integer likeduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.likeSchoolName
     *
     * @mbg.generated
     */
    private String likeschoolname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.likedSchoolName
     *
     * @mbg.generated
     */
    private String likedschoolname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.id
     *
     * @return the value of likes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.id
     *
     * @param id the value for likes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.likeUserId
     *
     * @return the value of likes.likeUserId
     *
     * @mbg.generated
     */
    public Integer getLikeuserid() {
        return likeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.likeUserId
     *
     * @param likeuserid the value for likes.likeUserId
     *
     * @mbg.generated
     */
    public void setLikeuserid(Integer likeuserid) {
        this.likeuserid = likeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.likedUserId
     *
     * @return the value of likes.likedUserId
     *
     * @mbg.generated
     */
    public Integer getLikeduserid() {
        return likeduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.likedUserId
     *
     * @param likeduserid the value for likes.likedUserId
     *
     * @mbg.generated
     */
    public void setLikeduserid(Integer likeduserid) {
        this.likeduserid = likeduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.update_time
     *
     * @return the value of likes.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.update_time
     *
     * @param updateTime the value for likes.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.add_time
     *
     * @return the value of likes.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.add_time
     *
     * @param addTime the value for likes.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.deleted
     *
     * @return the value of likes.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.deleted
     *
     * @param deleted the value for likes.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.likeSchoolName
     *
     * @return the value of likes.likeSchoolName
     *
     * @mbg.generated
     */
    public String getLikeschoolname() {
        return likeschoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.likeSchoolName
     *
     * @param likeschoolname the value for likes.likeSchoolName
     *
     * @mbg.generated
     */
    public void setLikeschoolname(String likeschoolname) {
        this.likeschoolname = likeschoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.likedSchoolName
     *
     * @return the value of likes.likedSchoolName
     *
     * @mbg.generated
     */
    public String getLikedschoolname() {
        return likedschoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.likedSchoolName
     *
     * @param likedschoolname the value for likes.likedSchoolName
     *
     * @mbg.generated
     */
    public void setLikedschoolname(String likedschoolname) {
        this.likedschoolname = likedschoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", likeuserid=").append(likeuserid);
        sb.append(", likeduserid=").append(likeduserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", likeschoolname=").append(likeschoolname);
        sb.append(", likedschoolname=").append(likedschoolname);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Likes other = (Likes) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLikeuserid() == null ? other.getLikeuserid() == null : this.getLikeuserid().equals(other.getLikeuserid()))
            && (this.getLikeduserid() == null ? other.getLikeduserid() == null : this.getLikeduserid().equals(other.getLikeduserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getLikeschoolname() == null ? other.getLikeschoolname() == null : this.getLikeschoolname().equals(other.getLikeschoolname()))
            && (this.getLikedschoolname() == null ? other.getLikedschoolname() == null : this.getLikedschoolname().equals(other.getLikedschoolname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLikeuserid() == null) ? 0 : getLikeuserid().hashCode());
        result = prime * result + ((getLikeduserid() == null) ? 0 : getLikeduserid().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getLikeschoolname() == null) ? 0 : getLikeschoolname().hashCode());
        result = prime * result + ((getLikedschoolname() == null) ? 0 : getLikedschoolname().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table likes
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table likes
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        likeuserid("likeUserId", "likeuserid", "INTEGER", false),
        likeduserid("likedUserId", "likeduserid", "INTEGER", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        likeschoolname("likeSchoolName", "likeschoolname", "VARCHAR", false),
        likedschoolname("likedSchoolName", "likedschoolname", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table likes
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table likes
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}