package com.school.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_user_id
     *
     * @mbg.generated
     */
    private Integer signUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.signed_user_id
     *
     * @mbg.generated
     */
    private Integer signedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_school_name
     *
     * @mbg.generated
     */
    private String signSchoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.signed_school_name
     *
     * @mbg.generated
     */
    private String signedSchoolName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_user_id
     *
     * @return the value of sign.sign_user_id
     *
     * @mbg.generated
     */
    public Integer getSignUserId() {
        return signUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_user_id
     *
     * @param signUserId the value for sign.sign_user_id
     *
     * @mbg.generated
     */
    public void setSignUserId(Integer signUserId) {
        this.signUserId = signUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.signed_user_id
     *
     * @return the value of sign.signed_user_id
     *
     * @mbg.generated
     */
    public Integer getSignedUserId() {
        return signedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.signed_user_id
     *
     * @param signedUserId the value for sign.signed_user_id
     *
     * @mbg.generated
     */
    public void setSignedUserId(Integer signedUserId) {
        this.signedUserId = signedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.update_time
     *
     * @return the value of sign.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.update_time
     *
     * @param updateTime the value for sign.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.add_time
     *
     * @return the value of sign.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.add_time
     *
     * @param addTime the value for sign.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.deleted
     *
     * @return the value of sign.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.deleted
     *
     * @param deleted the value for sign.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.status
     *
     * @return the value of sign.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.status
     *
     * @param status the value for sign.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_school_name
     *
     * @return the value of sign.sign_school_name
     *
     * @mbg.generated
     */
    public String getSignSchoolName() {
        return signSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_school_name
     *
     * @param signSchoolName the value for sign.sign_school_name
     *
     * @mbg.generated
     */
    public void setSignSchoolName(String signSchoolName) {
        this.signSchoolName = signSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.signed_school_name
     *
     * @return the value of sign.signed_school_name
     *
     * @mbg.generated
     */
    public String getSignedSchoolName() {
        return signedSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.signed_school_name
     *
     * @param signedSchoolName the value for sign.signed_school_name
     *
     * @mbg.generated
     */
    public void setSignedSchoolName(String signedSchoolName) {
        this.signedSchoolName = signedSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", signUserId=").append(signUserId);
        sb.append(", signedUserId=").append(signedUserId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", status=").append(status);
        sb.append(", signSchoolName=").append(signSchoolName);
        sb.append(", signedSchoolName=").append(signedSchoolName);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sign other = (Sign) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSignUserId() == null ? other.getSignUserId() == null : this.getSignUserId().equals(other.getSignUserId()))
            && (this.getSignedUserId() == null ? other.getSignedUserId() == null : this.getSignedUserId().equals(other.getSignedUserId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSignSchoolName() == null ? other.getSignSchoolName() == null : this.getSignSchoolName().equals(other.getSignSchoolName()))
            && (this.getSignedSchoolName() == null ? other.getSignedSchoolName() == null : this.getSignedSchoolName().equals(other.getSignedSchoolName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSignUserId() == null) ? 0 : getSignUserId().hashCode());
        result = prime * result + ((getSignedUserId() == null) ? 0 : getSignedUserId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSignSchoolName() == null) ? 0 : getSignSchoolName().hashCode());
        result = prime * result + ((getSignedSchoolName() == null) ? 0 : getSignedSchoolName().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sign
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sign
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        signUserId("sign_user_id", "signUserId", "INTEGER", false),
        signedUserId("signed_user_id", "signedUserId", "INTEGER", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        status("status", "status", "INTEGER", true),
        signSchoolName("sign_school_name", "signSchoolName", "VARCHAR", false),
        signedSchoolName("signed_school_name", "signedSchoolName", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}