package com.school.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class SignExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public SignExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public SignExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public SignExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        SignExample example = new SignExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public SignExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public SignExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSignUserIdIsNull() {
            addCriterion("sign_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSignUserIdIsNotNull() {
            addCriterion("sign_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSignUserIdEqualTo(Integer value) {
            addCriterion("sign_user_id =", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdNotEqualTo(Integer value) {
            addCriterion("sign_user_id <>", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdGreaterThan(Integer value) {
            addCriterion("sign_user_id >", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_user_id >=", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdLessThan(Integer value) {
            addCriterion("sign_user_id <", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("sign_user_id <=", value, "signUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignUserIdLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignUserIdIn(List<Integer> values) {
            addCriterion("sign_user_id in", values, "signUserId");
            return (Criteria) this;
        }

        public Criteria andSignUserIdNotIn(List<Integer> values) {
            addCriterion("sign_user_id not in", values, "signUserId");
            return (Criteria) this;
        }

        public Criteria andSignUserIdBetween(Integer value1, Integer value2) {
            addCriterion("sign_user_id between", value1, value2, "signUserId");
            return (Criteria) this;
        }

        public Criteria andSignUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_user_id not between", value1, value2, "signUserId");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdIsNull() {
            addCriterion("signed_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdIsNotNull() {
            addCriterion("signed_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdEqualTo(Integer value) {
            addCriterion("signed_user_id =", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdNotEqualTo(Integer value) {
            addCriterion("signed_user_id <>", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdGreaterThan(Integer value) {
            addCriterion("signed_user_id >", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("signed_user_id >=", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdLessThan(Integer value) {
            addCriterion("signed_user_id <", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("signed_user_id <=", value, "signedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedUserIdLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedUserIdIn(List<Integer> values) {
            addCriterion("signed_user_id in", values, "signedUserId");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdNotIn(List<Integer> values) {
            addCriterion("signed_user_id not in", values, "signedUserId");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdBetween(Integer value1, Integer value2) {
            addCriterion("signed_user_id between", value1, value2, "signedUserId");
            return (Criteria) this;
        }

        public Criteria andSignedUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("signed_user_id not between", value1, value2, "signedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("`status` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameIsNull() {
            addCriterion("sign_school_name is null");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameIsNotNull() {
            addCriterion("sign_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameEqualTo(String value) {
            addCriterion("sign_school_name =", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameNotEqualTo(String value) {
            addCriterion("sign_school_name <>", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameGreaterThan(String value) {
            addCriterion("sign_school_name >", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("sign_school_name >=", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameLessThan(String value) {
            addCriterion("sign_school_name <", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("sign_school_name <=", value, "signSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignSchoolNameLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("sign_school_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameLike(String value) {
            addCriterion("sign_school_name like", value, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameNotLike(String value) {
            addCriterion("sign_school_name not like", value, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameIn(List<String> values) {
            addCriterion("sign_school_name in", values, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameNotIn(List<String> values) {
            addCriterion("sign_school_name not in", values, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameBetween(String value1, String value2) {
            addCriterion("sign_school_name between", value1, value2, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignSchoolNameNotBetween(String value1, String value2) {
            addCriterion("sign_school_name not between", value1, value2, "signSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameIsNull() {
            addCriterion("signed_school_name is null");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameIsNotNull() {
            addCriterion("signed_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameEqualTo(String value) {
            addCriterion("signed_school_name =", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameNotEqualTo(String value) {
            addCriterion("signed_school_name <>", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameNotEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameGreaterThan(String value) {
            addCriterion("signed_school_name >", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameGreaterThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("signed_school_name >=", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameGreaterThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameLessThan(String value) {
            addCriterion("signed_school_name <", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameLessThanColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("signed_school_name <=", value, "signedSchoolName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andSignedSchoolNameLessThanOrEqualToColumn(Sign.Column column) {
            addCriterion(new StringBuilder("signed_school_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameLike(String value) {
            addCriterion("signed_school_name like", value, "signedSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameNotLike(String value) {
            addCriterion("signed_school_name not like", value, "signedSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameIn(List<String> values) {
            addCriterion("signed_school_name in", values, "signedSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameNotIn(List<String> values) {
            addCriterion("signed_school_name not in", values, "signedSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameBetween(String value1, String value2) {
            addCriterion("signed_school_name between", value1, value2, "signedSchoolName");
            return (Criteria) this;
        }

        public Criteria andSignedSchoolNameNotBetween(String value1, String value2) {
            addCriterion("signed_school_name not between", value1, value2, "signedSchoolName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbg.generated
         */
        private SignExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        protected Criteria(SignExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public SignExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(Sign.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(Sign.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table sign
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sign
         *
         * @mbg.generated
         */
        void example(com.school.model.SignExample example);
    }
}