package com.school.dao;

import com.school.model.Roletoauthorities;
import com.school.model.RoletoauthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletoauthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    long countByExample(RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int deleteByExample(RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int insert(Roletoauthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int insertSelective(Roletoauthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    Roletoauthorities selectOneByExample(RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    Roletoauthorities selectOneByExampleSelective(@Param("example") RoletoauthoritiesExample example, @Param("selective") Roletoauthorities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    List<Roletoauthorities> selectByExampleSelective(@Param("example") RoletoauthoritiesExample example, @Param("selective") Roletoauthorities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    List<Roletoauthorities> selectByExample(RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    Roletoauthorities selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Roletoauthorities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    Roletoauthorities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Roletoauthorities record, @Param("example") RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Roletoauthorities record, @Param("example") RoletoauthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Roletoauthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletoauthorities
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Roletoauthorities record);
}