package com.school.dao;

import com.school.model.Usertorole;
import com.school.model.UsertoroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsertoroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    long countByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int deleteByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int insert(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int insertSelective(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    Usertorole selectOneByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    Usertorole selectOneByExampleSelective(@Param("example") UsertoroleExample example, @Param("selective") Usertorole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    List<Usertorole> selectByExampleSelective(@Param("example") UsertoroleExample example, @Param("selective") Usertorole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    List<Usertorole> selectByExample(UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    Usertorole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Usertorole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    Usertorole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usertorole record, @Param("example") UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usertorole record, @Param("example") UsertoroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usertorole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertorole
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usertorole record);
}